### ISSUE TITLE
Howto set the iLO Server Name and Server FQDN

### ISSUE THREAD

**Issue by willifehler** [HewlettPackard/ilo-ansible-collection#36]
Hey there,

is it already possible to set the Server Name and Server FQDN? (not the iLO hostname)

Cheers - Willi

**Comment by willifehler** [comment]
![ilo-servername-and-fqdn](https://github.com/user-attachments/assets/3b23babf-7984-4870-b651-4df9d64766e9)

**Comment by willifehler** [comment]
This is what I'm trying to change.

**Comment by willifehler** [comment]
I was able to get the Server Name working by using:

```
    - name: Set BIOS attributes
      community.general.redfish_config:
        category: Systems
        command: SetBiosAttributes
        resource_id: 1
        baseuri: "{{ ansible_host }}"
        username: "{{ ilo_user }}"
        password: "{{ ilo_password }}"
        bios_attributes:
          ServerName: "{{ ilo_servername }}"
      register: biossettings
```
