### ISSUE TITLE
Insert Virtual Media not working

### ISSUE THREAD

**Issue by willifehler** [HewlettPackard/ilo-ansible-collection#37]
Hey there, I'm trying to attach an iSO file into my iLO:

```
- name: Insert Virtual Media
   community.general.redfish_command:
     category: Manager
     command: VirtualMediaInsert
     baseuri: "{{ ansible_host }}"
     username: "root"
     password: "{{ password }}"
     virtual_media:
     image_url: 'http://....iso'
     media_types:
       - CD
       - DVD
     resource_id: BMC
   tags: test
```

```
fatal: [..]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "../bin/python3.12"}, "changed": false, "msg": "System resource BMC not found"
```

Did I miss something?

**Comment by donzef** [comment]
Instead of using `BMC` for your `{ManagerId}`, have you tried tried to use `1` ? 

iLO's manager URI is `/redfish/v1/Managers/1` , not `/redfish/v1/Managers/BMC`.

**Comment by willifehler** [comment]
Hi @donzef,

you mean the task should look this?

```
- name: Insert Virtual Media
   community.general.redfish_command:
   category: Manager
   command: VirtualMediaInsert
   baseuri: "{{ ansible_host }}"
   username: "root"
   password: "{{ password }}"
   virtual_media:
   mage_url: 'http://.....iso'
   media_types:
     - CD
     - DVD
   resource_id: 1
```

Cheers - Willi
