### ISSUE TITLE
Failed to create Volumes in HPE machine with redfish_config

### ISSUE THREAD

**Issue by colbacc8** [HewlettPackard/ilo-ansible-collection#46]
I’m trying to use ansible and redfish to configure HPE machines with ILO5 v3.0.9

Most of the commands worked, but I’m getting trouble with the volume creation that uses the community.general.redfish_config module.

The following is an example of the code that I’m trying to execute to create a RAID0 volume on the disk number 2:
```
- name: Create vdi volumes RAID0
  community.general.redfish_config:
    category: Systems
    command: CreateVolume
    baseuri: "{{ inventory_hostname }}"
    username: "{{ ilo_username }}"
    password: "{{ ilo_password }}"
    storage_subsystem_id: "DE09B000"
    volume_details:
      Name: "Disk 2 NoRAID"
      RAIDType: "RAID0"
      Drives: 
        - "/redfish/v1/Systems/1/Storage/DE09B000/Drives/2" 
```

the first issue is that it asks me to specify the required parameter CapacityBytes which is not specified in any example.
Even if I add the CapacityBytes parameter with the size of the disk converted from terabytes in bytes, I receive a HTTP 400 error on a POST request with a message: “The operation failed due to an internal error.”

Moreover, if I try to use the ilorest command line, everything works without the need of the CapacityBytes parameter.
