### ISSUE TITLE
Task to finish the POST

### ISSUE THREAD

**Issue by willifehler** [HewlettPackard/ilo-ansible-collection#47]
Hey there,

I'm trying to create Logical Volumes on a MegaRAID Controller.

My Ansible task:

```
  - name: Create MegaRAID RAID1 LogicalDrive
      ansible.builtin.uri:
        url: https://{{ ansible_host }}/redfish/v1/Systems/1/Storage/DE040000/Volumes/
        validate_certs: false
        method: POST
        user: "{{ ilo_user }}"
        password: "{{ ilo_password }}"
        force_basic_auth: true
        body_format: json
        status_code: 200
        return_content: true
        headers:
          Content-Type: application/json
        timeout: 120
        body: "{{ ilo_megaraid_raid1_logical_drive | to_json }}"
      delegate_to: localhost
      when: ilo_megaraid_raid1_logical_drive is defined
```

The issue that I'm facing is that I have to wait that the POST is complete. Is there any way to boot into the Intelligent Provisioning to make sure the POST has completed?

Cheers - Willi
