### ISSUE TITLE
Example for ilo_snmp needs to be updated

### ISSUE THREAD

**Issue by akadoya** [HewlettPackard/ilo-ansible-collection#52]
https://galaxy.ansible.com/ui/repo/published/hpe/ilo/content/module/ilo_snmp/

### Current Example:

```
  - name: Get SNMP V3 Users
    ilo_snmp:
      category: Manager
      command: GetSnmpV3Users
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
```

This should be  GetSNMP**v3**Users according to this definition. (But, this definition is not visible from the public documentation page on Galaxy web site so I had to spend a while wondering where the error is coming from.... really appreciate if you could update the doc!

https://github.com/HewlettPackard/ilo-ansible-collection/blob/main/plugins/modules/ilo_snmp.py#L263
