### ISSUE TITLE
SetBootOrder returns HTTP error 400

### ISSUE THREAD

**Issue by QCU87Z** [HewlettPackard/ilo-ansible-collection#9]
I am having issues using this collection trying to get the boot order.

When I try the following
```
- name: Set boot order
  community.general.redfish_config:
    category: Systems
    command: SetBootOrder
    boot_order:
      - Boot000E
      - Boot0022
      - Boot001B
    baseuri: ilo.bla
    auth_token: token.bla
```

I get back FAILED
msg: HTTP Error 400 on PATCH request to 'https://ilo.bla/redfish/v1/Systems/1/
extended message: '[{MessageArgs': ['BootOrder', '1', '22', '22'], 'MessageId': 'iLO.2.14.ArrayPropertyOutOfBound'}]'

I have been able to set other bios settings with out issue. Effectivity I want to set the boot order to USB, PCI IPv4 PXE, Local drive

How do I use this collection to change and set the boot order.
